# Generated by Django 3.0.4 on 2020-03-10 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cd_library', '0002_auto_20200310_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerid',
            name='albumID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_library.Album'),
        ),
        migrations.CreateModel(
            name='ContentCategoryId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_library.Album')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_library.ContentCategory')),
            ],
        ),
    ]
