# Generated by Django 3.0.4 on 2020-03-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_library', '0003_auto_20200310_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='public/albums/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
