# Generated by Django 3.0.4 on 2020-03-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_library', '0004_auto_20200310_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumType',
            field=models.CharField(choices=[('a', 'Album'), ('p', 'Playlist')], default='p', max_length=1),
        ),
    ]
