# Generated by Django 3.0.4 on 2020-03-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_library', '0005_album_albumtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerid',
            old_name='albumID',
            new_name='album',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(default='Records', max_length=255),
        ),
    ]
