# Generated by Django 3.0.4 on 2020-03-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cd_library', '0007_auto_20200310_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover',
            new_name='coverImage',
        ),
    ]
