# Generated by Django 3.0.4 on 2020-03-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cd_library', '0008_auto_20200310_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='coverImage',
            new_name='cover',
        ),
    ]
