# Generated by Django 2.2.11 on 2020-03-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cd_library', '0009_auto_20200310_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='static/albums/'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('song', models.FileField(upload_to='static/tracks/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_library.Album')),
            ],
        ),
    ]
